<?php

echo implode("\n",[
"#!/usr/bin/env php",
"<?php",
"require_once 'vendor/autoload.php';",
"",
"use Stampy\Model\Class\ControllerHandler\BinControllerHandler;",
"use Stampy\Model\Class\ControllerHandler\JumpStart;",
"use Stampy\Model\Class\Singletone\ErrorHandler;",
"use Stampy\Model\Class\Singletone\BinErrorHandler;",
"use Stampy\Model\Class\\throwable\binError;",
"",
"try{",
"\t".'if(getenv("CLASS") && getenv("METHOD")){',
"\t\tnew JumpStart(getenv(\"CLASS\"),getenv(\"METHOD\"),\$argv)->start();",
"\t} else {",
"\t\t".'$controllersNameSpace = new \NamespaceHandler(__DIR__."/controller",getenv("NAMESPACE"));',
"\t\t".'new BinControllerHandler($controllersNameSpace->resolve(),$argv)->start();',
"\t}",
'} catch(Error $e) {',
"\t".'$errorHandler = &ErrorHandler::instance($e);',
"\t".'$errorHandler->debugInfo();',
'} catch(binError $e) {',
"\t".'$errorHandler = &BinErrorHandler::instance($e);',
"\t".'$errorHandler->correction();',
"}",
]);