#!/bin/bash
export $(grep -v '^#' .env | xargs)
 ext="extension=target/release/libstampy_php_cli.dylib" 
if [ $# -eq 0 ]; then
	php -d $ext /Users/jadbathore/Documents/coding/codding_rust/stampy/php-cli/init/console/bin
	exit 1
fi
args=""
for arg in "$@";do
	 args="$args $arg"
done
php -d $ext /Users/jadbathore/Documents/coding/codding_rust/stampy/php-cli/init/console/bin $args