#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';
require_once 'app/config.php';


use Stampy\Model\Class\ControllerHandler\BinControllerHandler;
use Stampy\Model\Class\ControllerHandler\JumpStart;
use Stampy\Model\Class\SingleTone\Errors\ErrorHandler;
use Stampy\Model\Class\SingleTone\Errors\BinErrorHandler;
use Stampy\Model\Class\Throwable\BinError;


try{
    if(getenv("CLASS") && getenv("METHOD")){
        new JumpStart(getenv("CLASS"),getenv("METHOD"),array_slice($argv,1))->start();
    } else {
        $controllersNameSpace = new \NamespaceHandler("./".getenv("ENTRY"),getenv("NAMESPACE"));
        new BinControllerHandler($controllersNameSpace->resolve(),$argv)->start();
    }
} catch(Error $err) {
    $errorHandler = &ErrorHandler::instance($err);
    $errorHandler->debugInfo();
} catch(binError $err) {
    $binErrorHandler = &BinErrorHandler::instance();
    $binErrorHandler->correctionInternalError($err);
} catch(\StampyException $err){
    $binErrorHandler = &BinErrorHandler::instance();
    $binErrorHandler->correctionStampyError($err);
}

