#!/bin/bash
export $(grep -v '^#' .env | xargs)
ext="extension=/usr/lib/php/20240924/stampy_php_cli.so" 
if [ $# -eq 0 ]; then
	php -d $ext index
	exit 1
fi

implode() {
    local sep="$1"; shift
    local arr=("$@")
    local IFS="$sep"
    echo "$*"
}

stdphp()
{
	local class="$1";
	local method="$2";
	local ERR="$3";
	local IN="$4";
	local rest=(${@:7});
	ERR=$([[ "$3" != "#" ]] && echo "2> tmp/$3");
	IN=$([[ "$4" != "#" ]] && echo "< tmp/$4");
	OUT=$([[ "$5" != "#" ]] && echo "> tmp/$5");
	eval "CLASS=\"$class\" METHOD=\"$method\" php -d $ext index $(implode " " ${rest[@]}) $IN $OUT $ERR"
}

args=$(implode " " "$@");
result=$(php -d $ext index $args);

if echo $result | grep -q "EXIT"; then
	arr=($result)
	stdphp ${arr[@]:1} $args
    exit 1;
else 
	echo "$result";
fi
