ARG BUILDPLATFORM

FROM --platform=$BUILDPLATFORM rust:latest 

RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    php \
    php-cli \
    php-dev \
    unzip \
    pkg-config \
    libssl-dev \
    libclang-dev \
    ca-certificates \
    && apt-get clean

COPY . /app 

ARG BIN_CONTENT

RUN cd app && cargo build --release

RUN echo "${BIN_CONTENT}"> /usr/local/bin/stampy && \
chmod 777 /usr/local/bin/stampy



CMD ["tail", "-f", "/dev/null"]