services:
  stampy:
    container_name: stampy
    build:
      context: ../
      dockerfile: ./docker-bin/dockerfile
      platforms:
        - linux/arm64
      args:
        ENTRY: ${ENTRY} 
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../test/${ENTRY}/:/${ENTRY}
      - ../test/.env:/.env
      - ../vendor:/vendor
      - ../composer.test.json:/composer.json
      - ../test.php:/index
      - ../stam:/usr/local/bin/stampy
      - ../:/tmp
