ARG BUILDPLATFORM


FROM --platform=$BUILDPLATFORM stampy:latest 

RUN EXT="/usr/lib/php/20240924/stampy_php_cli.so"  php docker-version/create_bin.php > usr/local/bin/stampy
# ENTRYPOINT ["stampy"];


COPY ./index ./


RUN apt-get update && apt-get install -y \
    unzip \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY ./composer.json ./
RUN mkdir app 

COPY ./app/Model ./app/Model

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install

RUN chmod 777 usr/local/bin/stampy
RUN chmod 777 index
